name: Backend Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main", "release" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Show workspace
        run: |
          pwd
          ls -la
          test -f pixi.toml
          echo "pixi.toml found!"

      - name: Test conda-forge connectivity
        run: |
          curl -I --http1.1 https://conda.anaconda.org/conda-forge/linux-64/repodata.json.zst
          curl -I --http2 https://conda.anaconda.org/conda-forge/linux-64/repodata.json.zst
      - name: Setup pixi
        uses: prefix-dev/setup-pixi@v0.10.2
        with:
          pixi-version: v0.66.0
          log-level: vvv
      - name: Test
        run: pixi run test
