name: Backend Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main", "release" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: prefix-dev/setup-pixi@v0.10.2
        with:
          pixi-version: v0.66.0
          working-directory: ../
      - run: pixi run test
